#Build selon le json si aucune target n'est fournie
[build]
target = "x86_64-blog_os.json"

#Permet de recompiler core et d'activer les méthodes de mémoire (memcpy, memset, etc.)
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"